set_option doc.verso true

/-! Exercise authored syntax and generated constants in the documentation inventory. -/

/-- An authored enumerated value that also generates deriving helpers. -/
inductive Choice where
  /-- Store the supplied natural number. -/
  | value (payload : Nat)
  deriving Repr, DecidableEq

/-- An authored record with an explicit constructor and grouped fields. -/
structure Data where
  /-- Construct a record from its three field values. -/
  create ::
  /-- Two independently authored natural-number fields. -/
  (first second : Nat)
  /-- An optional natural-number field; use {lean}`0` when it is unnecessary. -/
  third : Nat := 0

/-- A record whose default constructor is generated by the compiler. -/
structure ImplicitConstructor where
  /-- The field is authored even though its constructor is generated. -/
  amount : Nat

/-- This authored definition deliberately looks like a deriving helper. -/
def instReprPretend : Nat := 1

namespace LooksGenerated

/-- This authored definition deliberately looks like a compiler example. -/
def _example : Nat := 2

end LooksGenerated

/-- A Unicode declaration tests exact UTF-16 compiler/source coordinates. -/
def «µ_value» : Nat := 3

/-- An explicit anonymous instance has authored documentation on its keyword. -/
instance : Inhabited Data := ⟨⟨0, 0, 0⟩⟩

/-- A private helper has no public documentation obligation. -/
private def ignoredPrivate : Nat := 0

example : True := by trivial
example : True := by trivial

/-- A declaration docstring can compile temporary commands without exporting them.
```lean
def temporaryDocValue : Nat := 4
example : temporaryDocValue = 4 := rfl
```
-/
def documentedWithCommands : Nat := 4
