import VerifierConformance.Json
open SqliteVerifier.Conformance
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
def fixture : Case :=
  { version := 1,
    schemaSql := "CREATE TABLE t(id INTEGER NOT NULL,v BLOB,UNIQUE(id));",
    migrationSql := "INSERT INTO t(id,v) VALUES(2,0);",
    schema := [{ name := "t",
                 columns := [{ name := "id",
                               affinity := SqliteVerifier.Affinity.integer,
                               declaredType := SqliteVerifier.DeclaredType.canonical,
                               notNull := true,
                               defaultValue := none },
                             { name := "v",
                               affinity := SqliteVerifier.Affinity.blob,
                               declaredType := SqliteVerifier.DeclaredType.canonical,
                               notNull := false,
                               defaultValue := none }],
                 properties := { primaryKey := [], uniqueKeys := [["id"]], indexes := [] } }],
    initial := [("t",
                 { columns := [{ name := "id",
                                 affinity := SqliteVerifier.Affinity.integer,
                                 declaredType := SqliteVerifier.DeclaredType.canonical,
                                 notNull := true,
                                 defaultValue := none },
                               { name := "v",
                                 affinity := SqliteVerifier.Affinity.blob,
                                 declaredType := SqliteVerifier.DeclaredType.canonical,
                                 notNull := false,
                                 defaultValue := none }],
                   rows := [{ rowid := 1, values := [SqliteVerifier.Value.integer 1, SqliteVerifier.Value.blob []] }],
                   properties := { primaryKey := [], uniqueKeys := [["id"]], indexes := [] } })],
    script := [SqliteVerifier.Statement.insert
                 "t"
                 ["id", "v"]
                 [SqliteVerifier.Value.integer 2, SqliteVerifier.Value.integer 0]],
    nativeTrace := [{ visible := [("t",
                                   { columns := [{ name := "id",
                                                   affinity := SqliteVerifier.Affinity.integer,
                                                   declaredType := SqliteVerifier.DeclaredType.canonical,
                                                   notNull := true,
                                                   defaultValue := none },
                                                 { name := "v",
                                                   affinity := SqliteVerifier.Affinity.blob,
                                                   declaredType := SqliteVerifier.DeclaredType.canonical,
                                                   notNull := false,
                                                   defaultValue := none }],
                                     rows := [{ rowid := 1,
                                                values := [SqliteVerifier.Value.integer 1,
                                                           SqliteVerifier.Value.blob []] }],
                                     properties := { primaryKey := [], uniqueKeys := [["id"]], indexes := [] } })],
                      persisted := [("t",
                                     { columns := [{ name := "id",
                                                     affinity := SqliteVerifier.Affinity.integer,
                                                     declaredType := SqliteVerifier.DeclaredType.canonical,
                                                     notNull := true,
                                                     defaultValue := none },
                                                   { name := "v",
                                                     affinity := SqliteVerifier.Affinity.blob,
                                                     declaredType := SqliteVerifier.DeclaredType.canonical,
                                                     notNull := false,
                                                     defaultValue := none }],
                                       rows := [{ rowid := 1,
                                                  values := [SqliteVerifier.Value.integer 1,
                                                             SqliteVerifier.Value.blob []] }],
                                       properties := { primaryKey := [], uniqueKeys := [["id"]], indexes := [] } })],
                      transactionOpen := false,
                      primaryCode := 0,
                      extendedCode := 0 },
                    { visible := [("t",
                                   { columns := [{ name := "id",
                                                   affinity := SqliteVerifier.Affinity.integer,
                                                   declaredType := SqliteVerifier.DeclaredType.canonical,
                                                   notNull := true,
                                                   defaultValue := none },
                                                 { name := "v",
                                                   affinity := SqliteVerifier.Affinity.blob,
                                                   declaredType := SqliteVerifier.DeclaredType.canonical,
                                                   notNull := false,
                                                   defaultValue := none }],
                                     rows := [{ rowid := 1,
                                                values := [SqliteVerifier.Value.integer 1,
                                                           SqliteVerifier.Value.blob []] },
                                              { rowid := 2,
                                                values := [SqliteVerifier.Value.integer 2,
                                                           SqliteVerifier.Value.integer 0] }],
                                     properties := { primaryKey := [], uniqueKeys := [["id"]], indexes := [] } })],
                      persisted := [("t",
                                     { columns := [{ name := "id",
                                                     affinity := SqliteVerifier.Affinity.integer,
                                                     declaredType := SqliteVerifier.DeclaredType.canonical,
                                                     notNull := true,
                                                     defaultValue := none },
                                                   { name := "v",
                                                     affinity := SqliteVerifier.Affinity.blob,
                                                     declaredType := SqliteVerifier.DeclaredType.canonical,
                                                     notNull := false,
                                                     defaultValue := none }],
                                       rows := [{ rowid := 1,
                                                  values := [SqliteVerifier.Value.integer 1,
                                                             SqliteVerifier.Value.blob []] },
                                                { rowid := 2,
                                                  values := [SqliteVerifier.Value.integer 2,
                                                             SqliteVerifier.Value.integer 0] }],
                                       properties := { primaryKey := [], uniqueKeys := [["id"]], indexes := [] } })],
                      transactionOpen := false,
                      primaryCode := 0,
                      extendedCode := 0 }],
    requirements := [],
    provenance := [("fixture", "hypothesis"),
                   ("sourceId", "2025-11-04 19:38:17 fb2c931ae597f8d00a37574ff67aeed3eced4e5547f9120744ae4bfa8e74527b"),
                   ("nativeError", "")] }
#guard match Lean.Json.parse "{\"version\": 1, \"schemaSql\": \"CREATE TABLE t(id INTEGER NOT NULL,v BLOB,UNIQUE(id));\", \"migrationSql\": \"INSERT INTO t(id,v) VALUES(2,0);\", \"schema\": [{\"name\": \"t\", \"columns\": [{\"name\": \"id\", \"affinity\": \"integer\", \"declaredType\": \"canonical\", \"notNull\": true, \"defaultValue\": null}, {\"name\": \"v\", \"affinity\": \"blob\", \"declaredType\": \"canonical\", \"notNull\": false, \"defaultValue\": null}], \"properties\": {\"primaryKey\": [], \"uniqueKeys\": [[\"id\"]], \"indexes\": []}}], \"initial\": [[\"t\", {\"columns\": [{\"name\": \"id\", \"affinity\": \"integer\", \"declaredType\": \"canonical\", \"notNull\": true, \"defaultValue\": null}, {\"name\": \"v\", \"affinity\": \"blob\", \"declaredType\": \"canonical\", \"notNull\": false, \"defaultValue\": null}], \"properties\": {\"primaryKey\": [], \"uniqueKeys\": [[\"id\"]], \"indexes\": []}, \"rows\": [{\"rowid\": 1, \"values\": [{\"integer\": {\"value\": 1}}, {\"blob\": {\"bytes\": []}}]}]}]], \"script\": [{\"insert\": {\"table\": \"t\", \"columns\": [\"id\", \"v\"], \"values\": [{\"integer\": {\"value\": 2}}, {\"integer\": {\"value\": 0}}]}}], \"nativeTrace\": [{\"visible\": [[\"t\", {\"columns\": [{\"name\": \"id\", \"affinity\": \"integer\", \"declaredType\": \"canonical\", \"notNull\": true, \"defaultValue\": null}, {\"name\": \"v\", \"affinity\": \"blob\", \"declaredType\": \"canonical\", \"notNull\": false, \"defaultValue\": null}], \"properties\": {\"primaryKey\": [], \"uniqueKeys\": [[\"id\"]], \"indexes\": []}, \"rows\": [{\"rowid\": 1, \"values\": [{\"integer\": {\"value\": 1}}, {\"blob\": {\"bytes\": []}}]}]}]], \"persisted\": [[\"t\", {\"columns\": [{\"name\": \"id\", \"affinity\": \"integer\", \"declaredType\": \"canonical\", \"notNull\": true, \"defaultValue\": null}, {\"name\": \"v\", \"affinity\": \"blob\", \"declaredType\": \"canonical\", \"notNull\": false, \"defaultValue\": null}], \"properties\": {\"primaryKey\": [], \"uniqueKeys\": [[\"id\"]], \"indexes\": []}, \"rows\": [{\"rowid\": 1, \"values\": [{\"integer\": {\"value\": 1}}, {\"blob\": {\"bytes\": []}}]}]}]], \"transactionOpen\": false, \"primaryCode\": 0, \"extendedCode\": 0}, {\"visible\": [[\"t\", {\"columns\": [{\"name\": \"id\", \"affinity\": \"integer\", \"declaredType\": \"canonical\", \"notNull\": true, \"defaultValue\": null}, {\"name\": \"v\", \"affinity\": \"blob\", \"declaredType\": \"canonical\", \"notNull\": false, \"defaultValue\": null}], \"properties\": {\"primaryKey\": [], \"uniqueKeys\": [[\"id\"]], \"indexes\": []}, \"rows\": [{\"rowid\": 1, \"values\": [{\"integer\": {\"value\": 1}}, {\"blob\": {\"bytes\": []}}]}, {\"rowid\": 2, \"values\": [{\"integer\": {\"value\": 2}}, {\"integer\": {\"value\": 0}}]}]}]], \"persisted\": [[\"t\", {\"columns\": [{\"name\": \"id\", \"affinity\": \"integer\", \"declaredType\": \"canonical\", \"notNull\": true, \"defaultValue\": null}, {\"name\": \"v\", \"affinity\": \"blob\", \"declaredType\": \"canonical\", \"notNull\": false, \"defaultValue\": null}], \"properties\": {\"primaryKey\": [], \"uniqueKeys\": [[\"id\"]], \"indexes\": []}, \"rows\": [{\"rowid\": 1, \"values\": [{\"integer\": {\"value\": 1}}, {\"blob\": {\"bytes\": []}}]}, {\"rowid\": 2, \"values\": [{\"integer\": {\"value\": 2}}, {\"integer\": {\"value\": 0}}]}]}]], \"transactionOpen\": false, \"primaryCode\": 0, \"extendedCode\": 0}], \"requirements\": [], \"provenance\": [[\"fixture\", \"hypothesis\"], [\"sourceId\", \"2025-11-04 19:38:17 fb2c931ae597f8d00a37574ff67aeed3eced4e5547f9120744ae4bfa8e74527b\"], [\"nativeError\", \"\"]]}" with
  | .ok json => json == Lean.toJson fixture
  | .error _ => false
theorem checkedCase : checkCase fixture = true := by decide +kernel
#print axioms checkedCase
#print axioms unsupported_not_checked
#print axioms trace_final
