/* The public API of the parser library: grammar lookup, input checks and JSON documents.
**
** The build generates library_grammars.inc, which names each grammar's prefix and
** identity, and library_metadata.inc, which holds the metadata document. Each grammar's
** parse function comes from library_grammar.c. The documents keep the format of the
** sqlite-parser executable, except that "grammar" replaces "profile": one grammar can
** serve several releases.
*/
#include "library.h"
#include "runtime.h"

typedef void (*GrammarParse)(Context *ctx, const char *text, int size);

#define GRAMMAR(prefix, identity) void prefix##_parse(Context *ctx, const char *text, int size);
#include "library_grammars.inc"
#undef GRAMMAR

/* Each grammar identity of the library and the parse function built for it. */
static const struct { const char *identity; GrammarParse parse; } library_grammars[] = {
#define GRAMMAR(prefix, identity) {identity, prefix##_parse},
#include "library_grammars.inc"
#undef GRAMMAR
};

/* The metadata document, generated by the build from the dialect table and the sources. */
static const char library_metadata[] =
#include "library_metadata.inc"
;

/* The input limit of the executable: larger texts give RESOURCE_LIMIT at offset 0. */
#define LIBRARY_INPUT_LIMIT (1024 * 1024)

/* A growing output text; failed records an allocation failure, after which appends stop. */
typedef struct { char *data; size_t length, capacity; int failed; } Document;

/* Append size bytes, doubling the capacity when needed. */
static void document_append(Document *document, const char *text, size_t size){
  if(document->failed) return;
  if(document->length + size + 1 > document->capacity){
    size_t capacity = document->capacity ? document->capacity : 4096;
    while(document->length + size + 1 > capacity) capacity *= 2;
    char *data = realloc(document->data, capacity);
    if(!data){ document->failed = 1; return; }
    document->data = data;
    document->capacity = capacity;
  }
  memcpy(document->data + document->length, text, size);
  document->length += size;
  document->data[document->length] = 0;
}

/* Append NUL-terminated text. */
static void document_text(Document *document, const char *text){
  document_append(document, text, strlen(text));
}

/* Append a decimal integer, as printf's %d writes it. */
static void document_number(Document *document, int value){
  char digits[16];
  int size = snprintf(digits, sizeof digits, "%d", value);
  document_append(document, digits, (size_t)size);
}

/* Validate UTF-8 and reject NUL: SQLite's C API otherwise silently truncates input. */
static int utf8_valid(const unsigned char *text, size_t size){
  for(size_t i = 0; i < size;){
    unsigned c = text[i++], value;
    int tail;
    if(c == 0) return 0;
    if(c < 128) continue;
    if(c >= 194 && c <= 223){ tail = 1; value = c & 31; }
    else if(c >= 224 && c <= 239){ tail = 2; value = c & 15; }
    else if(c >= 240 && c <= 244){ tail = 3; value = c & 7; }
    else return 0;
    int length = tail;
    if(i + (size_t)tail > size) return 0;
    while(tail--){ c = text[i++]; if((c & 192) != 128) return 0; value = (value << 6) | (c & 63); }
    if((length == 2 && value < 2048) || (length == 3 && value < 65536)
       || value > 0x10ffff || (value >= 0xd800 && value <= 0xdfff)) return 0;
  }
  return 1;
}

/* Write the executable's JSON for ctx, with the grammar identity in place of the release. */
static void output(Document *document, const Context *ctx, const char *identity){
  if(ctx->error || !ctx->accepted){
    document_text(document, "{\"status\":\"");
    document_text(document, ctx->error == 2 ? "RESOURCE_LIMIT" : "INPUT_ERROR");
    document_text(document, "\",\"offset\":");
    document_number(document, ctx->offset);
    document_text(document, "}\n");
    return;
  }
  document_text(document, "{\"status\":\"PARSED\",\"grammar\":\"");
  document_text(document, identity);
  document_text(document, "\",\"root\":");
  document_number(document, ctx->root);
  document_text(document, ",\"nodes\":[");
  for(int i = 0; i < ctx->count; i++){
    const Node *node = &ctx->nodes[i];
    document_text(document, i ? ",{\"symbol\":\"" : "{\"symbol\":\"");
    document_text(document, node->symbol);
    document_text(document, "\",\"start\":");
    document_number(document, node->start);
    document_text(document, ",\"end\":");
    document_number(document, node->end);
    document_text(document, ",\"children\":[");
    for(int j = 0; j < node->count; j++){
      if(j) document_text(document, ",");
      document_number(document, node->children[j]);
    }
    document_text(document, "]}");
  }
  document_text(document, "]}\n");
}

/* Check the input as the executable does, then parse a NUL-terminated copy: the
** tokenizer reads past the end of a token until it finds a NUL byte. */
static int parse_checked(GrammarParse parse, Context *ctx, const unsigned char *sql, size_t length){
  if(length > LIBRARY_INPUT_LIMIT){ ctx->error = 2; return SQLITE_VERIFIER_PARSER_OK; }
  if(!utf8_valid(sql, length)){ ctx->error = 1; return SQLITE_VERIFIER_PARSER_OK; }
  char *text = calloc(length + 4, 1);
  if(!text) return SQLITE_VERIFIER_PARSER_NO_MEMORY;
  if(length) memcpy(text, sql, length);
  parse(ctx, text, (int)length);
  free(text);
  return SQLITE_VERIFIER_PARSER_OK;
}

/* Hand the finished document to the caller, or release it after an allocation failure. */
static int finish(Document *document, char **result, size_t *length){
  if(document->failed){ free(document->data); return SQLITE_VERIFIER_PARSER_NO_MEMORY; }
  *result = document->data;
  *length = document->length;
  return SQLITE_VERIFIER_PARSER_OK;
}

int sqlite_verifier_parser_metadata(char **document, size_t *length){
  Document copy = {0};
  document_append(&copy, library_metadata, sizeof library_metadata - 1);
  return finish(&copy, document, length);
}

int sqlite_verifier_parser_parse(const char *grammar, const unsigned char *sql, size_t length,
                                 char **document, size_t *document_length){
  size_t count = sizeof library_grammars / sizeof library_grammars[0];
  size_t index = 0;
  while(index < count && (!grammar || strcmp(grammar, library_grammars[index].identity))) index++;
  if(index == count) return SQLITE_VERIFIER_PARSER_UNKNOWN_GRAMMAR;
  Context ctx = {0};
  Document result = {0};
  int status = parse_checked(library_grammars[index].parse, &ctx, sql, length);
  if(status == SQLITE_VERIFIER_PARSER_OK) output(&result, &ctx, library_grammars[index].identity);
  for(int i = 0; i < ctx.count; i++) free(ctx.nodes[i].children);
  free(ctx.nodes);
  if(status != SQLITE_VERIFIER_PARSER_OK) return status;
  return finish(&result, document, document_length);
}

void sqlite_verifier_parser_free(char *document){
  free(document);
}
