CREATE TABLE parent(id INTEGER PRIMARY KEY, label TEXT NOT NULL);
CREATE TABLE child(id INTEGER PRIMARY KEY, parent_id REFERENCES parent(id) ON DELETE CASCADE);
CREATE TABLE audit(parent_id INTEGER);
CREATE TRIGGER inserted AFTER INSERT ON parent BEGIN
  INSERT INTO audit VALUES(new.id);
  INSERT INTO audit VALUES(new.id);
END;
